spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.1"

loans:
  message: "Welcome to EazyBank loans related qa APIs "
  contactDetails:
    name: "Quality Grega - QA"
    email: "qa@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
